// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajhoatywklkpsrdcavxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqaG9hdHl3a2xrcHNyZGNhdnhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODk3ODIsImV4cCI6MjA2NTU2NTc4Mn0.e9D-x1qq1AbcsycFiAr1K5WR2ou9awNJTfOihG0jWWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);